name: mscm
channels:
  - conda-forge
dependencies:
  - parallel=20230322
  - python=3.10.9
  - pdm=2.4.9
  - pygraphviz=1.10
  - quarto=1.2.335
  - r=4.2
  - r-dplyr=1.1.1
  - r-ggplot2=3.4.1
  - r-here=1.0.1
  - r-knitr=1.42
  - r-lubridate=1.9.2
  - r-mgcv=1.8_42
  - r-patchwork=1.1.2
  - r-purrr=1.0.1
  - r-readr=2.1.4
  - r-remotes=2.4.2
  - r-reticulate=1.26
  - r-rmarkdown=2.21
  - r-sf=1.0_12
  - r-stringr=1.5.0
  - r-tidyr=1.3.0
  - r-units=0.8_1
